### ISSUE TITLE
Can't generate sphinx-js documentation

### ISSUE THREAD

**Issue by amirouche** [erikrose/sphinx-js#20]
When I do make html in my sphinx project it fails and the following is reported:

```python
# Sphinx version: 1.6.2
# Python version: 3.5.3 (CPython)
# Docutils version: 0.13.1 release
# Jinja2 version: 2.9.6
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/home/amirouche/.virtualenvs/socialite/lib/python3.5/site-packages/sphinx/cmdline.py", line 305, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/home/amirouche/.virtualenvs/socialite/lib/python3.5/site-packages/sphinx/application.py", line 234, in __init__
    self._init_builder()
  File "/home/amirouche/.virtualenvs/socialite/lib/python3.5/site-packages/sphinx/application.py", line 312, in _init_builder
    self.emit('builder-inited')
  File "/home/amirouche/.virtualenvs/socialite/lib/python3.5/site-packages/sphinx/application.py", line 489, in emit
    return self.events.emit(event, self, *args)
  File "/home/amirouche/.virtualenvs/socialite/lib/python3.5/site-packages/sphinx/events.py", line 79, in emit
    results.append(callback(*args))
  File "/home/amirouche/.virtualenvs/socialite/lib/python3.5/site-packages/sphinx_js/jsdoc.py", line 27, in run_jsdoc
    doclets = load(temp)
  File "/usr/lib/python3.5/json/__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```

I am using sphinx-js 2.0.1.

**Comment by amirouche** [comment]
Have look at https://github.com/amirouche/socialite/commit/3309fd3d861c2719be2ef49530205e5f367fdb4f

**Comment by amirouche** [comment]
It works with 2.0.0

**Comment by amirouche** [comment]
https://github.com/erikrose/sphinx-js/commit/e535e3689a459b28ee4287b2d7de4b5c340bd146 introduced the bug

**Comment by amirouche** [comment]
\cc @jhkennedy

**Comment by jhkennedy** [comment]
What do you get when you run `python -c "import locale; print(locale.getpreferredencoding(False))"`?

**Comment by amirouche** [comment]
```
(socialite) amirouche@ubudec:~/src/python/socialite$ python -c "import locale; print(locale.getpreferredencoding(False))"
UTF-8
```

**Comment by jhkennedy** [comment]
@amirouche and @erikrose I was able to recreate this using Python 3.4 and 3.5, but not in python 3.6. Subprocess introduced a couple of methods dealing with encoding in python 3.6, so those changes likely "fixed" this bug for earlier pythons. 

I'll play around with some more explicit handling of the temp file encoding/decoding tomorrow so that earlier versions of python 3 are supported.

**Comment by rstemmer** [comment]
Hi
Same(?) problem with Python **3.6** / sphinx-js 2.0.1

```
# Sphinx version: 1.6.3                                                                        
# Python version: 3.6.2 (CPython)                                                              
# Docutils version: 0.13.1 release                                                             
# Jinja2 version: 2.9.6                                                                        
# Last messages:                                                                               

# Loaded extensions:                                                                           
Traceback (most recent call last):                                                             
  File "/usr/lib/python3.6/site-packages/sphinx/cmdline.py", line 305, in main                 
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)                                 
  File "/usr/lib/python3.6/site-packages/sphinx/application.py", line 234, in __init__         
    self._init_builder()                                                                       
  File "/usr/lib/python3.6/site-packages/sphinx/application.py", line 312, in _init_builder    
    self.emit('builder-inited')                                                                
  File "/usr/lib/python3.6/site-packages/sphinx/application.py", line 489, in emit             
    return self.events.emit(event, self, *args)                                                
  File "/usr/lib/python3.6/site-packages/sphinx/events.py", line 79, in emit                   
    results.append(callback(*args))                                                            
  File "/usr/lib/python3.6/site-packages/sphinx_js/jsdoc.py", line 27, in run_jsdoc            
    doclets = load(temp)                                                                       
  File "/usr/lib/python3.6/json/__init__.py", line 299, in load                                
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)                  
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads                               
    return _default_decoder.decode(s)                                                          
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode                               
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())                                          
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode                           
    raise JSONDecodeError("Expecting value", s, err.value) from None                           
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0) 
```

**Comment by jhkennedy** [comment]
@amirouche, @rstemmer I believe #27 should fix these issues you're encountering; can you give it a try?

**Comment by jhkennedy** [comment]
Actually, @rstemmer it looks the `temp` file which stores the output of the jsdoc command is empty. If you run `jsdoc` independently what do you get?

**Comment by rstemmer** [comment]
#27 did not fix _my_ problem. The problem was in front of the screen :)

I digged into the code and recognized that `app.config.js_source_path` never gets checked if it is a vaild path.
I just set an absolute path to a directory that had a javascript inside. Worked!

**Comment by erikrose** [comment]
I guess that would be a good thing to check. :-)
